# Config file for pre-commit:
# 1. Install pre-commit with "conda install -c conda-forge pre_commit"
# 2. Copy and replace ./.git/hooks/pre-commit.sample with hooks/pre-commit file
# 3. Add this file to root of git repository and modify enabled hooks as necessary

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    #-   id: autopep8-wrapper
    #-   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    #-   id: debug-statements
    #-   id: name-tests-test
    #-   id: requirements-txt-fixer
    #-   id: flake8
    -   id: check-symlinks
    -   id: check-merge-conflict
    -   id: check-added-large-files
